services:
  backup:
    build: .
    command: python app.py
    volumes:
      - ./config.cfg:/app/config.cfg:ro
      - /opt/storage:/app/backups/storage
      - /opt/npm:/app/backups/npm
      - /home/atxy2k/echecopar_sitemaps:/app/backups/sitemaps  

